export const LOAD_CONTACTS = "CONTACTS/LOAD_CONTACTS";
export const LOADING_CONTACTS = "CONTACTS/LOADING_CONTACTS";
export const LOAD_CONTACTS_SUCCESS = "CONTACTS/LOAD_CONTACTS_SUCCESS";
export const LOAD_CONTACTS_FAILED = "CONTACTS/LOAD_CONTACTS_FAILED";

export const SYNC_CONTACTS = "CONTACTS/SYNC_CONTACTS";
export const SYNCING_CONTACTS = "CONTACTS/SYNCING_CONTACTS";
export const SYNC_CONTACTS_SUCCESS = "CONTACTS/SYNC_CONTACTS_SUCCESS";
export const SYNC_CONTACTS_FAILED = "CONTACTS/SYNC_CONTACTS_FAILED";
