//Entities
export const LOAD_ENTITIES = 'entity/LOAD_ENTITIES';
export const LOADING_ENTITIES = 'entity/LOADING_ENTITIES';
export const LOAD_ENTITIES_SUCCESS = 'entity/LOAD_ENTITIES_SUCCESS';
export const LOAD_ENTITIES_FAILED = 'entity/LOAD_ENTITIES_FAILED';

export const LOAD_ENTITY_CONVERSATION = 'entity/LOAD_ENTITY_CONVERSATION';
export const LOADING_ENTITY_CONVERSATION = 'entity/LOADING_ENTITY_CONVERSATION';
export const LOAD_ENTITY_CONVERSATION_SUCCESS =
  'entity/LOAD_ENTITY_CONVERSATION_SUCCESS';
export const LOAD_ENTITY_CONVERSATION_FAILED =
  'entity/LOAD_ENTITY_CONVERSATION_FAILED';
export const CLEAR_ENTITY_CONVERSATION = 'entity/CLEAR_ENTITY_CONVERSATION';

export const SEND_COMMAND = 'entity/SEND_COMMAND';
export const SENDING_COMMAND = 'entity/SENDING_COMMAND';
export const SEND_COMMAND_SUCCESS = 'entity/SEND_COMMAND_SUCCESS';
export const SEND_COMMAND_FAILED = 'entity/SEND_COMMAND_FAILED';
export const APPEND_NEW_CHAT_TO_ENTITY = 'entity/APPEND_NEW_CHAT_TO_ENTITY';
